---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prizmdoc-server-config
data:
  # See https://help.accusoft.com/PrizmDoc/latest/HTML/central-configuration.html
  # for details on configuring Prizmdoc Server
  prizm-services-config.yml: |-
    license.key: YOUR_LICENSE_KEY
    license.solutionName: YOUR_SOLUTION_NAME
    network.publicPort: 18681
    network.internalStartingPort: 19000
    network.clustering.enabled: false
    logging.directory: "/logs"
    logging.daysToKeep: 1
    cache.directory: "/data/cache"
    workFiles.directory: "/data/cache/workfileCache"
    userDocuments.directory: "/data/cache/userDocuments"
    viewing.allowDocumentDownload: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prizmdoc-server-logs
  labels:
    app.kubernetes.io/name: prizmdoc-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prizmdoc-server-headless
  labels:
    app.kubernetes.io/name: prizmdoc-server
    app.kubernetes.io/component: headless-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prizmdoc-server
  clusterIP: None
  ports:
    - name: public
      port: 18681
      protocol: TCP
      targetPort: public
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prizmdoc-server
  labels:
    app.kubernetes.io/name: prizmdoc-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prizmdoc-server
  serviceName: prizmdoc-server-headless
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prizmdoc-server
    spec:
      containers:
        - name: prizmdoc-server
          image: docker.io/accusoft/prizmdoc-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ACCEPT_EULA
              value: "YES"
          ports:
            - name: public
              containerPort: 18681
              protocol: TCP
          volumeMounts:
            - name: prizmdoc-server-config
              mountPath: /config
              readOnly: true
            - name: prizmdoc-server-data
              mountPath: /data
            - name: prizmdoc-server-logs-internal
              mountPath: /logs
          resources:
            limits:
              cpu: "2.0"
              memory: 6Gi
            requests:
              cpu: "500m"
              memory: 3Gi
          # livenessProbe:
          #   httpGet:
          #     path: /PCCIS/V1/Service/Current/Health
          #     port: public
          #     scheme: HTTP
          #   initialDelaySeconds: 60
          #   periodSeconds: 30
          #   timeoutSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /PCCIS/V1/Service/Current/Health
          #     port: public
          #     scheme: HTTP
          #   initialDelaySeconds: 60
          #   periodSeconds: 30
          #   timeoutSeconds: 5
        - name: prizmdoc-server-logging-agent
          image: docker.io/fluent/fluent-bit:1.8.10
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: prizmdoc-server-fluent-config
              mountPath: /fluent-bit/etc/
            - name: prizmdoc-server-logs-internal
              mountPath: /logs
            - name: prizmdoc-server-logs
              mountPath: /processed-logs
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
      volumes:
        - name: prizmdoc-server-config
          configMap:
            name: prizmdoc-server-config
        - name: prizmdoc-server-logs-internal
          emptyDir: {}
        - name: prizmdoc-server-logs
          persistentVolumeClaim:
            claimName: prizmdoc-server-logs
        - name: prizmdoc-server-fluent-config
          configMap:
            name: prizmdoc-server-fluent-config
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: prizmdoc-server-data
        labels:
          app.kubernetes.io/name: prizmdoc-server
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prizmdoc-server
  labels:
    app.kubernetes.io/name: prizmdoc-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prizmdoc-server
  ports:
    - name: public
      port: 18681
      protocol: TCP
      targetPort: public
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prizmdoc-server-fluent-config
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush           5
        Daemon          off
        Parsers_File    parsers.conf

    [INPUT]
        Name            tail
        Tag             ${POD_NAME}.<pccis>.<file_name>
        Tag_Regex       /logs/(?<pccis>Pccis[012])/(?<file_name>.*)
        Path            /logs/Pccis[012]/ImagingServices.log
        DB              /logs/logs.db
        Parser          json
        Read_from_Head  True
        Skip_Long_Lines On
        Mem_Buf_Limit   25MB

    [INPUT]
        Name            tail
        Tag             ${POD_NAME}.<pccis>.<file_name>
        Tag_Regex       /logs/(?<pccis>Pccis[012])/(?<file_name>.*)
        Path            /logs/Pccis[012]/console.log
        DB              /logs/logs.db
        Read_from_Head  True
        Skip_Long_Lines On
        Mem_Buf_Limit   1MB

    [INPUT]
        Name            tail
        Tag             ${POD_NAME}.<file_name>
        Tag_Regex       /logs/(?<file_name>.*)
        Path            /logs/*.log
        Exclude_Path    /logs/*.*.log,/logs/PccErrors.log,/logs/FileViewer.log,/logs/mongod.log
        DB              /logs/logs.db
        Parser          json
        Read_from_Head  True
        Skip_Long_Lines On
        Mem_Buf_Limit   25MB

    [INPUT]
        Name            tail
        Tag             ${POD_NAME}.<file_name>
        Tag_Regex       /logs/(?<file_name>.*)
        Path            /logs/plb.*.log
        DB              /logs/logs.db
        Parser          json
        Read_from_Head  True
        Skip_Long_Lines On
        Mem_Buf_Limit   25MB

    [INPUT]
        Name            tail
        Tag             ${POD_NAME}.<file_name>
        Tag_Regex       /logs/(?<file_name>.*)
        Path            /logs/PccErrors.log
        DB              /logs/logs.db
        Parser          json
        Read_from_Head  True
        Skip_Long_Lines On
        Mem_Buf_Limit   2MB

    [INPUT]
        Name            tail
        Tag             ${POD_NAME}.<file_name>
        Tag_Regex       /logs/(?<file_name>.*)
        Path            /logs/mongod.log
        DB              /logs/logs.db
        Read_from_Head  True
        Skip_Long_Lines On
        Mem_Buf_Limit   2MB

    [INPUT]
        Name            tail
        Tag             ${POD_NAME}.<file_name>
        Tag_Regex       /logs/(?<file_name>.*)
        Path            /logs/*.console*.log
        DB              /logs/logs.db
        Read_from_Head  True
        Skip_Long_Lines On
        Mem_Buf_Limit   2MB

    [OUTPUT]
        Name            file
        Match           *
        Format          plain
        Path            /processed-logs
  parsers.conf: |-
    [PARSER]
        Name            json
        Format          json
        Time_Key        time
        Time_Format     %Y-%m-%dT%H:%M:%S.%LZ
        Time_Keep       On
